### ISSUE TITLE
Copy is not safe to use with concurrent requests

### ISSUE THREAD

**Issue by FZambia** [yousuf64/shift#6]
Hello @yousuf64 

Awesome library, many thanks for working on it! Please take a look at this test:

```go
func TestParams_Copy(t *testing.T) {
	t.Run("Copy should not be affected when source is reset and reused", func(t *testing.T) {
		p := newParams(1)
		p.setKeys(&[]string{"foo"})
		p.appendValue("bar")

		cp := p.Copy()

		p.reset()
		p.setKeys(&[]string{"foo"})
		p.appendValue("bar2")

		val := cp.Get("foo")
		assert(t, val == "bar", fmt.Sprintf("expected: bar, got: %s", val))
	})
}
```

Outputs `expected: bar, got: bar2`

Slices in copy still reference to the original ones. If I am not missing sth here – pooling params and re-using them may result in copy corruption at the moment.

**Comment by yousuf64** [comment]
Hi @FZambia, thanks for trying out **shift**. I hope you have had a good experience so far.

And also, massive thanks for noticing and reporting the issue; I'll have a look and fix the issue :)
